version: '3.1'
services:
    ansible-master:
        container_name: ansible-master
        build: master/
        container_name: ansible-master
        volumes:
            - $PWD/ansible-key:/root/.ssh/id_rsa
            - $PWD/configs/hosts:/etc/ansible/hosts
            - $PWD/playbooks:/tmp/playbooks/
    ansible-node1:
        build: node1/
        container_name: ansible-node1
        ports:
          - "22"
